<?php
/**
 * Created by PhpStorm.
 * User: wlodek
 * Date: 08/04/16
 * Time: 11:29
 */

namespace App\Controllers\Admin;


class Users extends \Core\Controller
{

    /**
     * Before filter
     *
     * @return void
     */
    protected function before()
    {
//        parent::before(); // TODO: Change the autogenerated stub
        //make sure admin user is logged in for example
        //return false;

    }

    /**
     * Show the index page
     *
     * @return void
     */
    public function indexAction()
    {
        echo 'User admin index';
    }


}